  language: ruby

cache: bundler

sudo: false

branches:
  except:
  - gh-pages
  - next_doc_release
env:
  global:
  - TRAVIS_BUILD=true

rvm:
  - 1.9.3
  - jruby-19mode
  - 2.1
  - 2.2

before_install:
  - gem update --system
  - gem update bundler

script: bundle exec rake ci

notifications:
  slack:
    secure: bPNEO9bbp7o45iwXeltMfpDHOJtZExcRY7OLm+XdppZgcCGGTMXNpJyceiwavSKYkw4QfGx6BzD4EnhD2OP9Zb/o+in26l7yKMl20yv1KqKuH2dYT1bkxp688La1pGgnelONhf3VRx/JHoqZkPostKpQy9KM5gyTy40+RKvvcgk=

